### ISSUE TITLE
Total removal of a taxa barely present in the blanks but highly represented in the samples

### ISSUE THREAD

**Issue by fedeboio** [donaldtmcknight/microDecon#1]
Hello, 

I am posting here because I am a bit confused about one of the results I've obtained from microDecon. I am not an expert so I apologize if what I am asking is banal.
 
I am interested in the bacterial communities associated with arthropods (insects and spiders) and I believe microDecon is perfect for me as several common contaminant taxa of extraction kits and reagents could be actually present in my samples and I did not want to completely remove from my samples the taxa detected in the blanks and controls. 
Before the sequencing, the arthropods samples were macerated in sterile water that then was inoculated on agar plates for culture-dependent microbiological analysis, the DNA was then extracted from the macerates and the library was prepared for Illumina Miseq sequencing. For the sequencing run, I've included a blank (i.e. sample that underwent all the library preparation steps) and the washing water that I've used for the processing of the samples. Overall, I've used 5 different batches of sterile water to wash the bugs. To process the samples on microDecon I have grouped the samples washed with the same washing water batch and I've decontaminated them independently using the following commands: 

`decontam_ww1 <- decon(data=ww1, numb.blanks=2, numb.ind=4, taxa=T)`
the blanks include the sequencing blank and the water used for washing the bugs. 

`decon_table_ww1 <- decontam_ww1$decon.table `
To obtain the decontaminated table 

`oturemoved_ww1 <- decontam_ww1$OTUs.removed`
To obtain the list of OTUs removed

I've repeated these steps per each group of samples. 

My question regards one of the most abundant taxa present in the samples before the decontamination. This taxon was present in many arthropod samples and in each washing water batch except batch 4. In the blank, only 26 reads of it were detected. I do not understand why after the decontamination, this taxon was kept in every sample washed with water 1, 2, 3 and 5 but it was one of the taxa completely removed from group 4, which was the only group of arthropods washed with a batch of water that was completely lacking this taxon. Could you please help me understand what happened?  Thank you very much.

**Comment by donaldtmcknight** [comment]
I am sorry that you are having this issue. To clarify, for each batch, you have both a water sample and a blank, and for batch 4, the OTU in question amplified in the blank, but not in the water? Is that correct?

If so, what is the distribution of reads like in your blank? microDecon operates on relative abundances, so if, for example, 26 was the highest read count for any OTU in the blank, it thinks that OTU is predominantly from contamination. If that OTU is unabundant (relatively) in the blank, however, then it should not have been totally removed from the samples unless it also had a very low abundance in the samples. From your description, however, it sounds like it was highly abundant. Was it actually present as a very large number of reads (suggesting true abundance) or was it simply present in many samples (which could be contamination)? I would need to look at your actual data to tell you for sure what is going on, which I'm happy to do if you'd like to email it to me.

Just to cover the obvious, your data are structured with OTU IDs in column 1, followed by two columns of blanks, followed by four columns of samples, followed by a taxa column, correct?

One other thought, how consistent are your blanks and water samples across batches? If they are very similar (you can evaluate this with stacked bar plots and/or Bray-Curtis dissimilarities), then I'd encourage you to do a single run with all the blanks, all the water samples, and all the samples. In other words, if it looks like the contamination was roughly the same for each batch, then you can pool them and will get better results. If the contamination is very different in each batch, however, then they should be run separately as you did. Again, I'm happy to help you evaluate this if you'd like.

A final thought is the thresh and prop.thresh arguments. Both work best with large numbers of samples. If you only have 4 or fewer samples in batch 4, then thresh will not do anything. However, if you have 5 or more, then thresh is set to 0.7 by default, and you may want to set it to a less stringent value or shut it off entirely (i.e., set it to 1). prop.thresh is always on by default (regardless of sample size), but for small numbers of samples, you often need to adjust its default setting (see the user manual for more details or feel free to ask me if it is unclear). You can also shut this option off if you feel it is unnecessary for your data (these filtering options are just final tidying up steps and do not affect the core decontamination function, but for small sample sizes, they can occasionally result in the total removal of OTUs that should have been retained in low numbers).

**Comment by donaldtmcknight** [comment]
I am leaving this here in case it is useful for anyone else. I spoke with fedeboio and examined their data. The issue was that the blank only had a total of 26 reads, all of which were for the OTU in question, while the water sample had many reads for multiple OTUs. microDecon assumes that all blanks are similar for a given run and averages them after transforming to proportions. Thus, including the blank where only one OTU amplified made microDecon treat that OTU as if it was a high source of contamination. In reality, the data suggest that there is significant contamination in the water batches, but, given that there were only 26 reads in the blank and they were all for a common OTU, it also suggests that there was no contamination from reagents, and the 26 reads in the blank simply represent an extremely minor level of inevitable cross-contaminaiton and/or index switching from a very common OTU. Therefore, only the water samples should be included in microDecon. It is very important to check for homogeneity of blanks before using microDecon.
